matrix:
  include:
    - language: c
      sudo: false
      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/newdigate/teensy-midi-looper/master/Software/install-travis-ci-arduino.sh)
      install:
        - arduino --install-library "MIDI Library","Adafruit SleepyDog Library","Adafruit FONA Library","Queue","SD","Adafruit GFX Library","Adafruit ST7735 Library","Encoder"
      script:
        - build_main_platforms
        
    - language: cpp
      sudo: false
      compiler:
        - clang
      before_install:
        - gcc -v && g++ -v && cmake --version
        - cd Software/arduino
        - mkdir cmake-build-debug
        - cd cmake-build-debug
        - cmake ..
        - make
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

notifications:
  email:
    on_success: change
    on_failure: change
