matrix:
  include:
    - language: c
      sudo: false
      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/newdigate/teensy-midi-looper/master/Software/install-travis-ci-arduino.sh)
      install:
        - arduino --install-library "MIDI Library","Adafruit SleepyDog Library","Adafruit FONA Library","Queue","SD","Adafruit GFX Library","Adafruit ST7735 Library","Encoder"
      script:
        - build_main_platforms
        
    - dist: trusty
      sudo: require
      language: cpp
      env: 
        - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
      compiler:
        - clang
      before_install:
        # Download and install recent cmake
        - |
          if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
            CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
            mkdir -p ${DEPS_DIR}/cmake
            travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
          fi
        - cd Software/arduino/cmake-build-debug
        - cmake ..
        - make
      install:
          # - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
          - echo ${PATH}
          - echo ${CXX}
          - ${CXX} --version
          - ${CXX} -v
          - echo TRAVIS_OS_NAME is ${TRAVIS_OS_NAME}
          
notifications:
  email:
    on_success: change
    on_failure: change
